[project]
id = "seddly"
name = "Seddly"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://seddly.com"

[auth.external.apple]
enabled = true
