import Foundation

struct CommitmentSharingService {
    /// Generates a formatted reminder message to send to the person who made the commitment.
    static func generateReminderMessage(for commitment: LocalCommitment) -> String {
        var message = "Hi \(commitment.entityName),\n\n"
        message += "This is a friendly reminder about a commitment:\n\n"
        message += "\"" + commitment.summary + "\"\n"

        if let deadline = commitment.deadline {
            let formatter = DateFormatter()
            formatter.dateStyle = .long
            let deadlineStr = formatter.string(from: deadline)

            if deadline < .now {
                let daysOverdue = Calendar.current.dateComponents([.day], from: deadline, to: .now).day ?? 0
                message += "\nThis was due by \(deadlineStr) (\(daysOverdue) day\(daysOverdue == 1 ? "" : "s") ago)."
            } else {
                message += "\nDue by: \(deadlineStr)"
            }
        }

        if let amount = commitment.dollarAmount {
            message += "\nAmount: $\(amount)"
        }

        message += "\n\n— Sent via Seddly (seddly.com)"
        return message
    }

    /// Generates a read-only summary link format (for web sharing when backend supports it).
    static func generateShareableLink(commitmentID: UUID) -> URL? {
        URL(string: "https://seddly.com/c/\(commitmentID.uuidString.lowercased().prefix(8))")
    }

    /// Generates a plain text summary suitable for dispute evidence.
    static func generateEvidenceSummary(for commitment: LocalCommitment) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .long

        var summary = "COMMITMENT RECORD\n"
        summary += String(repeating: "=", count: 30) + "\n"
        summary += "From: \(commitment.entityName)\n"
        summary += "Commitment: \(commitment.summary)\n"

        if let deadline = commitment.deadline {
            summary += "Deadline: \(formatter.string(from: deadline))\n"
        }
        if let amount = commitment.dollarAmount {
            summary += "Amount: $\(amount)\n"
        }

        summary += "Status: \(commitment.status.label)\n"
        summary += "Recorded: \(formatter.string(from: commitment.createdAt))\n"

        if commitment.source == .auto {
            summary += "Source: Auto-detected from screenshot"
            if let date = commitment.screenshotDate {
                summary += " (\(formatter.string(from: date)))"
            }
            summary += "\n"
        }

        if let notes = commitment.notes, !notes.isEmpty {
            summary += "\nNotes: \(notes)\n"
        }

        summary += "\n— Generated by Seddly (seddly.com)"
        return summary
    }
}
